# Generated by Django 4.0.4 on 2022-06-08 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='emailValidationUUID',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
